// ═══════════════════════════════════════════════════════════════════════════
// MISSING TRANSLATION KEYS - SINGLE-LINE JS FORMAT
// Norwegian Tax Calculator - 2026-03-15
// ═══════════════════════════════════════════════════════════════════════════

// ───────────────────────────────────────────────────────────────────────────
// EN (English) - Missing keys: salAntiRows, npvExamplesRows (+ 5 rows), npvTipsRows (+ 2 rows)
// ───────────────────────────────────────────────────────────────────────────

// EN salAntiRows (17 rows total)
    salAntiRows: [['— RELATED PARTIES —','The arm\'s length principle (§ 13-1)'],['What is a related-party relationship?','When two parties have common ownership interests or control that affects transactions between them','§ 13-1(1)'],['What happens if the price is wrong?','The Tax Agency can determine income/wealth by estimate — as if the related-party relationship did not exist','§ 13-1(3)'],['Party outside the EEA?','Reversed burden of proof — you must prove the price is correct','§ 13-1(2)'],['What is the arm\'s length principle?','Transactions between related parties must be priced as between independent parties','§ 13-1(4)'],['Which guidelines apply?','The OECD transfer pricing guidelines are applied','§ 13-1(4)'],['— ANTI-AVOIDANCE RULE —','The statutory GAAR (§ 13-2)'],['What is avoidance?','When a disposition is primarily motivated by tax benefits and does not withstand a holistic assessment','§ 13-2(2)'],['Condition 1: Main purpose?','The tax benefit must have been the predominant purpose of the disposition','§ 13-2(2)a'],['Condition 2: Holistic assessment?','The disposition is evaluated as a whole — business substance, size of tax benefit, whether the route was inappropriate, and whether rules are exploited contrary to purpose','§ 13-2(3) a–f'],['What happens on avoidance?','Taxation is carried out according to the economic substance of the disposition — not its form','§ 13-2(4)'],['Does it only apply to income tax?','No — also national insurance contributions, employer social security contributions and financial tax','§ 13-2(7)'],['— TAX POSITIONS WITHOUT CONNECTION —','Losses, positive balance etc. (§ 13-3)'],['What is a general tax position?','Losses carried forward, empty positive balance, balance on gain/loss account — positions without connection to a specific asset','§ 13-3'],['When does the position lapse?','On reorganisation (ch. 11) or change of ownership where exploitation of the position is the predominant motive','§ 13-3 a'],['What about tax liabilities?','Recognised as income without the right to offset against losses — and cannot form the basis for group contributions','§ 13-3 b'],['Who does this apply to?','Companies under § 2-2 (AS, ASA etc.) that are party to a reorganisation or have changed ownership','§ 13-3']],

// EN npvExamplesRows complete 16-row version (rows 11-16 are new additions)
    npvExamplesRows: [['— EXAMPLE 1: NEW MACHINE —','Manufacturing company evaluates new machine'],['Investment','1,000,000 kr'],['Cash flow per year','300,000 kr for 5 years (increased production, lower maintenance)'],['Discount rate','10% (WACC)'],['NPV','137,236 kr → Profitable! The investment returns more than 10%.'],['— EXAMPLE 2: RENTAL PROPERTY —','Private person evaluates buying rental property'],['Investment','3,000,000 kr (equity + loan)'],['Net rental income per year','150,000 kr (after interest, maintenance, tax)'],['Expected sale gain year 5','500,000 kr'],['Discount rate','7% (alternative return from stock market)'],['Assessment','Compare NPV with alternative investment in funds — consider risk and liquidity.'],['— EXAMPLE 3: STARTUP —','Entrepreneur evaluates new business'],['Investment','500,000 kr'],['Year 1-2','Negative: -100,000 and -50,000 (startup)'],['Year 3-5','Positive: 200,000, 300,000, 400,000'],['Important','Use higher discount rate (15-20%) for startups because risk is higher.']],

// EN npvTipsRows complete 11-row version (rows 10-11 are new additions)
    npvTipsRows: [['— GOOD ADVICE —',''],['Be conservative with estimates','It is better to be positively surprised than to lose money. Use realistic (not optimistic) cash flows.'],['Use the right discount rate','For companies: WACC. For individuals: alternative return. For risky projects: add 3-5%.'],['Don\'t forget residual value','Does the project have value after year 5? Include sale value or scrap value in the last year\'s cash flow.'],['Think about tax','Cash flows should be after tax. Remember that depreciation provides tax benefits.'],['— COMMON MISTAKES —',''],['Mixing cash flow and profit','NPV uses cash flow (money in/out), NOT accounting profit. Depreciation is not cash flow.'],['Forgetting working capital','New business often needs money tied up in inventory and receivables — this is an investment.'],['Too low discount rate','Using 3% (bank rate) instead of 10% (WACC) makes everything look profitable. Use the market rate.'],['Ignoring opportunity cost','The money you invest could be placed elsewhere. NPV analysis accounts for this via the discount rate.'],['Only looking at payback period','Short payback is nice, but a project that takes longer can have much higher NPV. Look at the whole picture.']],


// ───────────────────────────────────────────────────────────────────────────
// SO (Somali) - All missing keys
// ───────────────────────────────────────────────────────────────────────────

    // Basic labels
    calcHelpHint:'Ma baahan tahay caawin qalculator? →', bcDecLabel:'Decimals',

    // NPV How-to (10 rows)
    npvHowtoTitle:'Sidii loo isticmaalo qalculator-ka', npvHowtoDesc:'Tilmaam-tilmaam til NPV iyo IRR',
    npvHowtoRows: [['— TILLMAAM ILLAA TILLMAAM —','Sida loo qabaa falanqeynta mamuulka'],['1. Beelka mamuulka','Gali waxa aad mamuulistay hadda. Tusaale: karig, hanti, bilaabista mashruuc.'],['2. Tirada diskuntiga','Isticmaal doonista aad rabo ee hantida. Caadi ahaan WACC (8-12%) ama hantida kale. Tirada sare = micnaha xoogan.'],['3. Qiimaha lacag-bixida','Gali qiimaha lacag-bixida iinan (dakhli kaas oo kharash baxwaalka ah). Isticmaal qiyamyada iska dhegdheg ah.'],['4. Gacal Qareenta','Qalculator-ku waxaa kuutusi NPV, IRR, wakhtiga dib-u-celinta iyo tilmaamiga buuxnimada.'],['— SIDII AAD UGA AKHRISID NATIIJAADA —',''],['NPV (qiimaha hadda jirta ee laaxe)','NPV togan = mamuulka waxaa sii baxaya in badan oo loo baahan yahay. Inta badan, inta wanaag.'],['IRR (tirada midka u dhexgal ah)','Tirada taas oo dhigta NPV = 0. Isbaaro qiimaha aad rabo. IRR > doonista = mamuulka wanaagsan.'],['Wakhtiga dib-u-celinta','Inta jeer lagu dhamaadaa in aad celinno mamuulka. Yar ayaa wanaag — laakiin haldilo mamuulka wanaagsan iyada oo lagu jiro mudo.'],['Tilmaamiga buuxnimada (PI)','Qiimaha hadda jirta ee dakhliga iyo mamuulka. PI > 1 = buuxsama. PI 1.3 waxaa kaa keeni doonaa 30% dib hoo soo noqda sare oo aad doonisid.']],

    // NPV Examples (16 rows)
    npvExamplesTitle:'Tusaalooyin dunida dhab ah', npvExamplesDesc:'Gofyo caadiga ah ee mamuulka',
    npvExamplesRows: [['— TUSAALO 1: KARIG CUSUB —','Wakaarada soo saarka ayaa tiri karig cusub'],['Mamuulka','1,000,000 kr'],['Qiimaha lacag-bixida sannadba','300,000 kr 5 sanno (soo saarka badan, kayd yar)'],['Tirada diskuntiga','10% (WACC)'],['NPV','137,236 kr → Buuxsama! Mamuulka waxaa sii baxaya 10% ka badan.'],['— TUSAALO 2: HANTI LACAG-BIXIDA —','Qof gaar ah ayaa tiri hanti lacag-bixida loo iibsado'],['Mamuulka','3,000,000 kr (kayd iska qabso + qorshaha)'],['Dakhli lacag-bixida sannadba','150,000 kr (kahor riba, kayd, cashuur)'],['Guulka loo filayo 5 sanno','500,000 kr'],['Tirada diskuntiga','7% (guulka kale ee suuqa xusbaarka)'],['Qiyamynta','Isbaaro NPV iyo meelka kale ee mamuulka fonska — mahadsanid khatarta iyo caasimadka.'],['— TUSAALO 3: BILAABINTA —','Guurida ayaa tiri mamuul cusub'],['Mamuulka','500,000 kr'],['1-2 sanno','Halis: -100,000 iyo -50,000 (bilaabinta)'],['3-5 sanno','Wanaag: 200,000, 300,000, 400,000'],['Muhiim','Isticmaal tirada diskuntiga sare (15-20%) mamuulka bilaabinta sababtoo ah khatarta waa badan.']],

    // NPV Tips (11 rows)
    npvTipsTitle:'Tilmaamyo iyo khaladaadka caadiga ah', npvTipsDesc:'Isku day khaladaadka badan ee nooca ah',
    npvTipsRows: [['— TALOOYIN WANAAGSAN —',''],['Ahaansho qiymada','Waa ka wanaag in aad ku faraxdo kayga is weydiin. Isticmaal qiymada dhab ah (manna qiymada caadi marka lamaanay).'],['Isticmaal tirada diskuntiga saxda ah','Wakaaladda: WACC. Qof gaar ah: guulka kale. Mamuulka khatarta badan: ku dar 3-5%.'],['Maya iloowin qiymaha hadhaadhka ah','Miyuu mamuulka qiyam u leeyahay kaas oo 5 sanno? Gali qiymaha lacag-bixida ama scrap-ka 5 sanno ee ugu dambeeyay.'],['Ogsoo ay cashuurta','Qiymaha lacag-bixida waa in ay yihiin kaas oo cashuurta. Mahadsanid in avskrivninger ay siiso cashuur baxwaalka ah.'],['— KHALADAADKA CAADIGA AH —',''],['Isku dhex-marida qiimaha lacag-bixida iyo natiijaada','NPV isticmaala qiimaha lacag-bixida (lacag soo gala/baxda), MAHA natiijaada xisaabaadka. Avskrivninger maha qiimaha lacag-bixida.'],['Iloowin kaydka oo hawgashada ah','Wakaaladda cusub ayaa sida caadi ah u baahan lacag oo xiran lagasse iyo dib u celinta — waxaa kaa mamuulka.'],['Tirada diskuntiga yar tooda','Haddii aad isticmaasho 3% (banki riba) halka aad isticmaasho 10% (WACC), waxaa u muuqdaa wanaagsan oo dhan. Isticmaal qiymaha suuq-ka.'],['Iloowin qiymaha kale ee mamuulka','Lacagta aad mamuulistay waxaa laga yaabaa in ay lagu baahdo meelka kale. Falanqeynta NPV waxaa lagu fikirtaa via tirada diskuntiga.'],['Kaliya iska dhaaf wakhtiga dib-u-celinta','Wakhtiga gaaban oo dib-u-celinta ayaa wanaag, laakiin mamuulka wakhtiga dheer qab leh waxaa leh NPV badan oo badan. Ogsoo ay sawirka.']],


// ───────────────────────────────────────────────────────────────────────────
// TI (Tigrinya) - All missing keys
// ───────────────────────────────────────────────────────────────────────────

    // Basic labels
    calcHelpHint:'ሓገዝ ኣለኻ ብካልኩሌተር? →', bcDecLabel:'ዖፍ',

    // NPV How-to (10 rows)
    npvHowtoTitle:'ካሌኩሌተር መጠቀም ዝገበረ', npvHowtoDesc:'ደረጃ-ብ-ደረጃ መምራዓ ናብ NPV ን IRR',
    npvHowtoRows: [['— ደረጃ-ብ-ደረጃ —','ዘለውካ ምግምጋም ኢንቬስትመንት'],['1. ዓቐን ኢንቬስትመንት','ነቲ ውልቅ ዓቐን ኢንቬስትመንት ዋሒድ እዛ ሰዓት ተኸተል። ንኢስታንስ፣ ምስተከላ፣ ግብር፣ ምስ ፕሮጀክት።'],['2. ምጠሊ ምልክ','ምስ ፍለይካ መስመር ተወሃቦ። ብተመሃሩ WACC (8-12%) ወይ ዝተወሃወ ተመሃሩ። ዝተዓሪበ ምልክ = ጸልየ መስመር።'],['3. ስሙት ምልክ ገንዘብ','ተመልክት ተኣማሚዞ ገንዘብ ምልክ ሎሚ (ገቢ ይነግ-ወጻ ገብየት)። ስሩዓ ተዓባቦ ምጥቀም።'],['4. ኢዥራ ዘናብር','ካልኩሌተር ክህብካ NPV፣ IRR፣ ወቅት ምምለስ ን ምግምጋም ምልክ።'],['— ስኡ ብዝወሓደ ናትካ ምግምጋም ውጀት —',''],['NPV (ከፋፍሉ ዝርዝር ዋጋ)','ቅላሳ NPV = ኢንቬስትመንት ዝወጻ ዝውብኩ ምስ ተኣማሚዞ። እንተ ተዓሪበ ዋላ።'],['IRR (ውሉድ ምልክ ምመላስ)','ምልክ ብዘይ ውጀት ወደብ NPV = 0። ምስ ተኣማሚዞ ምልክ ምልክ። IRR > ተኣማሚዞ = ምጥቃ ኢንቬስትመንት።'],['ወቅት ምምለስ','ተቐወመ ወዮ ኢንቬስትመንት ምውጻ። ክትንቤ ናይ ምልክ — ግና ኣጋግዐ ምጥቃ ውጀት ዓዝዩ ሒዛ ውኸ።'],['ምግምጋም ምልክ (PI)','ንስባት ክንደይ ዋጋ ገቢ ናብ ኢንቬስትመንት። PI > 1 = ምጥቃ። PI 1.3 ሓጺር ይምልከት 30% ተመሃሩ ዝወጻ ስነ ተኣማሚዞ።']],

    // NPV Examples (16 rows)
    npvExamplesTitle:'ዋናይ ምሳሌታት', npvExamplesDesc:'ብልጫ ምግምጋም ኢንቬስትመንት',
    npvExamplesRows: [['— ምሳሌ 1: ሓዲስ ማሽን —','ቅርጳ-ብልጫ ተቓወምቲ ሓዲስ ማሽን'],['ኢንቬስትመንት','1,000,000 kr'],['ስሙት ምልክ ገንዘብ ዓመት','300,000 kr 5 ዓመት (ተጨምሪ ምፍጣር፣ ውሁድ ገሪድ)'],['ምጠሊ ምልክ','10% (WACC)'],['NPV','137,236 kr → ምጥቃ! ኢንቬስትመንት ይወጻ 10% ዝተወሃወ።'],['— ምሳሌ 2: ሃብቲ ምልክ ገንዘብ —','ግሉ ሰብ ትሕዋሱ ሃብቲ ምልክ ገንዘብ'],['ኢንቬስትመንት','3,000,000 kr (መሓላልዩ ካፒታል + ዋንታ)'],['ድሙዓዊ ምልክ ገንዘብ ዓመት','150,000 kr (ድሕር ምልክ፣ ገሪድ፣ ብርከት)'],['ተጨመረ ናጸግ ዓመት 5','500,000 kr'],['ምጠሊ ምልክ','7% (ዝተወሃወ ተሓሕዝ ሃብቲ ገበያ)'],['ምግምጋም','NPV ምስ ዝተወሃወ ኢንቬስትመንት ፈንድ — ብሌት ሮ ዝህበ ዘድሪስ።'],['— ምሳሌ 3: ምስ ምስ ሐዋሳ —','ሚሪ ሓዲስ ሞበላ'],['ኢንቬስትመንት','500,000 kr'],['1-2 ዓመት','ሳይ: -100,000 ን -50,000 (ሐዋሳ)'],['3-5 ዓመት','ይኹን: 200,000, 300,000, 400,000'],['ዋና','ተጠቀም ንሑሳ ምጠሊ ምልክ (15-20%) ምስ ሐዋሳ ምከናት ሮ ሳይ ዝበሃል።']],

    // NPV Tips (11 rows)
    npvTipsTitle:'ምርጋጻ ን ግኤ ስሪ ልምድ', npvTipsDesc:'ሂወት ሓዋሉ ስሪ ልምድ',
    npvTipsRows: [['— ብልጫ ምርጋጻ —',''],['ሓድሓድ ምስ ንብር','ብሓበሬታ ምግ ንብር ከ ዘይምስ ገንዘብ። ተጠቀም ዋናይ (ዘይ ንዓወትናዊ) ስሙት ምልክ ገንዘብ።'],['ተጠቀም ኩሌትለ ምጠሊ ምልክ','ምስተቓወምቲ: WACC። ግሉ ሰብ: ዝተወሃወ ተሓሕዝ። ብሳይ ኢንቬስትመንት: ተጨምር 3-5%።'],['ኣይምሕሉ ቀሪ ዋጋ','ኢንቬስትመንት ዓቐን ድሕር 5 ዓመት? ተግዛእ ምልክ ገነት ወይ scrap ዋጋ ዓመት 5 ካኢላ።'],['ክሙት ብርከት','ስሙት ምልክ ገንዘብ ብግዜ ድሕር ብርከት። ምብሌት ማሪ ሊቲ ዝውጻ ብርከት ነጋዥ።'],['— ልምድ ስሪ —',''],['ተቐልቦ ስሙት ምልክ ገንዘብ ከስድ ውጀት','NPV ተጠቀም ስሙት ምልክ ገንዘብ (ገንዘብ በምኮማ/ወጻ)፣ ዘይ ደብር ውጀት። ሊቲ ዘይ ስሙት ምልክ ገንዘብ።'],['ዘይምስ ሰራሕ ካፒታል','ሓዲስ ሞበላ ከ ብሩህ ዓቐን ገንዘብ ገበረ ዋቅ ን ዓወቲ — ኢ ኢንቬስትመንት።'],['ሳይ ምጠሊ ምልክ','ተጠቐመ 3% (ባንክ ምልክ) ደገፈትካ 10% (WACC)፣ ኩሉ ይምስ ምጥቃ። ተጠቀም ገበያ ምልክ።'],['ኣይምሕሉ ውሕደት ዋጋ','ገንዘብ ኢንቬስትመንት ከ ተኸዲም ካሌ። NPV ምግምጋም ይግምግም ኣዝ ምጠሊ ምልክ።'],['ኣይምዕበ ግጡ ወቅት ምምለስ','ንብር ወቅት ምምለስ ይኹን ምጥቃ፣ ግና ኢንቬስትመንት ቅሩብ ጊዜ ንስብ NPV ብዛ። ክሙ ምልክ።']],

// ═══════════════════════════════════════════════════════════════════════════
// END
// ═══════════════════════════════════════════════════════════════════════════
